package: plyr 
version: 'Plyr' 
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/video
page:
    title: 'Video'
    perm: video[]
    pjax: false
    icon: rex-icon fa-television
    subpages:
        help:  
             { title: 'translate:video_help',  icon: rex-icon fa-question-circle, subPath: README.md} 
requires:
    redaxo: '^5.6' 
    php:
        version: '>=5.7.0-beta3'
