package: video 
version: '1.3.1' 
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/video
page:
    title: 'Video'
    perm: video[]
    pjax: false
    icon: rex-icon fa-television
    subpages:
        main:  
             title: 'translate:title'    
        help:  
             title: 'translate:help' 
        module: 
             title: 'translate:module' 
requires:
    redaxo: '^5.3' 
    php:
        version: '>=5.6'
